### ISSUE TITLE
Generated files under version control?

### ISSUE THREAD

**Issue by awvwgk** [urbanjost/M_intrinsics#2]
I'm still trying to figure out this project and looking around a bit, apparently, a lot of generated files are under git version control here. Invoking:

```
make -C build-manpages
```

produces a huge diff in the generated HTML outputs and all over the place: `422 files changed, 30616 insertions(+), 24610 deletions(-)`.

I also noticed that make starts writing *outside* of the repository, at least it attempts to copy files into my home with:
```
[ -d $HOME/LIBRARY/libGPF/download/doc ] && cp ../md/*.man $HOME/LIBRARY/libGPF/download/doc/
```
I'm not clear what the rationale behind this is, but a wildcard copy to some other project seems potentially harmful to me. Also, this line will always fail unless the directory is present and make can actually copy the content there.

**Comment by urbanjost** [comment]
The copy was just  there for a few hours during some debugging. The ALL STOP is a specific extension that predates ERROR stop and was specifically for ensuring F- images all stopped more like MPI. Changed that to ERROR STOP.  Only the md/ directory is actual source. All the other files in man/  and doc/ are generated except for the BOOK* and .js* .  I do not know of any easy way to update the HTML pages on the github site so that it can be viewed on-line without including them in the .git files, and the manpages are there so that if someone downloads the project with fpm(1) they can use the files on any linux or unix platform. If this gets moved to fortran-lang I think the man/ and doc/ directories would be in .gitignore but as it is and because the files are so small that seems to work for now.

**Comment by awvwgk** [comment]
> The copy was just there for a few hours during some debugging.

Okay, I fetched again, still getting an error with this line:
```
which make.one >/dev/null 2>&1 && make.one libGPF
```

> The ALL STOP is a specific extension that predates ERROR stop and was specifically for ensuring F- images all stopped more like MPI. Changed that to ERROR STOP.

Thanks for the clarification.

>  I do not know of any easy way to update the HTML pages on the github site so that it can be viewed on-line without including them in the .git files, and the manpages are there so that if someone downloads the project with fpm(1) they can use the files on any linux or unix platform.

They could be built automatically and uploaded to a separate branch. I do something similar for the HTML documentation FORD generates for my projects. I might give it a try once I'm sure everything runs as expected on my machine.
